name: Reusable - Build and Test

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: 'ubuntu-latest'
        type: string
      java-version:
        required: false
        default: '17'
        type: string
      java-distribution:
        required: false
        default: 'temurin'
        type: string
      working-directory:
        required: false
        default: '.'
        type: string

jobs:
  reusable-build-and-test:
    runs-on: ${{ inputs.runner }}

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: |
          echo "Building and testing project..."
          ./gradlew build

      - name: Verify dependency licenses
        uses: jeanpierrefortune/keyple.keyple-actions/actions/dash-licenses@dash-licenses-v1
        with:
          working-directory: ${{ inputs.working-directory }}